# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import system_info_pb2 as proto_dot_system__info__pb2


class SystemInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SystemInfo = channel.unary_unary(
        '/SystemInfo/SystemInfo',
        request_serializer=proto_dot_system__info__pb2.SystemInfoRequest.SerializeToString,
        response_deserializer=proto_dot_system__info__pb2.SystemInfoResponse.FromString,
        )


class SystemInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SystemInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SystemInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SystemInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SystemInfo,
          request_deserializer=proto_dot_system__info__pb2.SystemInfoRequest.FromString,
          response_serializer=proto_dot_system__info__pb2.SystemInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SystemInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
